### DISCUSSION TITLE
Change Tag Colors in Chat Channels

### DISCUSSION THREAD

**Discussion by Catz87** [TownyAdvanced/Towny#4765] [Q&A] [answered]
Hello,
is it possible to change the chat channel tag colors to be different colors
when you talk in general chat I would like nation/town tags to be green
when you talk in town chat I would like nation/town tags to be blue
when you talk in ally chat the tags to be dark blue
when you talk in nation chat the tags to be gold
when you talk in local chat the tags to be a different color.

if I change the tag colors under tag_formats: it changes them for every channel. I am unable to change them on a per channel base.

my chatconfig.yml
```
chatconfigcomments: ''
 
channel_formats:
  # This is the format which will be used for GLOBAL chat/channels.
  # This is also the format used when you have modify_chat.enable: true, but use other plugins to handle chat.
  global: '{nationformatted}{townformatted}{title}{surname}{playername}&2:{msgcolour} {msg}'
  # TOWN channel types.
  town: '{nation}{town}{title}{surname}{playername}&b:{msgcolour} {msg}'
  # NATION channel types.
  nation: '{nationformatted} {townformatted}{townycolor}{townyprefix}{playername}{townypostfix}{permsuffix}&6:{msgcolour} {msg}'
  # ALLIANCE channel types.
  alliance: '{channelTag} {towntagoverride}{townycolor}{permprefix}{townyprefix}{playername}{townypostfix}{permsuffix}&3:{msgcolour} {msg}'
  # DEFAULT channel types.
  default: '{channelTag} {permprefix}{playername}{permsuffix}&f:{msgcolour} {msg}'
 
tag_formats:
  world: '&2[&f%s&f] '
  town: '&b[&3%s&f] '
  nation: '&6[&e%s&f] '
  # First %s is the nation tag, second is the town tag.
  # You may also use %t for the town tag and %n for the nation tag!
  both: '&f[&6%s&f|&3%s&f] '
 
colour:
  king: '&6'
  mayor: '&b'
  resident: '&f'
  nomad: '&f'
 
modify_chat:
  # When true Towny will format all ChannelTypes,
  # When false Towny will only format TOWN, NATION, ALLIANCE, DEFAULT types.
  # When false Towny will not format GLOBAL types, leaving other chat plugins to do the work.
  enable: 'true'
  # If true the chat formats will be read from below to allow per world formatting.
  # These can then be altered individually.
  per_world: 'false'
  # If true any player who speaks in a channel in which he cannot be heard,
  # either by being along in the channel or out-of-range of another player in his chat channel,
  # that player will see a message saying they cannot be heard.
  alone_message: 'false'
  # This allows you to set your alone message.
  alone_message_string: No one in range can hear you or you are alone in this channel.
 
# If true players will see [Towny] Modes set: general when they log in.
display_modes_set_on_join: 'true'
```
