### DISCUSSION TITLE
Modify channelTag colors for Local chat channel

### DISCUSSION THREAD

**Discussion by Catz87** [TownyAdvanced/Towny#4828] [Q&A] [answered]
<img width="416" alt="localchat" src="https://user-images.githubusercontent.com/79274157/112192286-d5ba0e00-8bd4-11eb-8263-e361c324fb4e.PNG">
Hello,
I am looking for a way to modify towny local chat colors. I have been able to do it with global, town, nation, and alliance. I do not see a local option in the channel_formats section. I have seen this done on other servers how is this possible?
I have posted my chatconfig.yml with the appropriate section i think should include the details needed. I have also included my channels.yml file

I have added a image of my chatconfig.yml better to read maby
Thank you for your support!

**chatconfig.yml**
```
channel_formats:
  # This is the format which will be used for GLOBAL chat/channels.
  # This is also the format used when you have modify_chat.enable: true, but use other plugins to handle chat.
  global: '{channelTag}{nationformatted}{townformatted}&a{playername}:{msgcolour} {msg}'
  # TOWN channel types.
  town: '{channelTag}{townformatted}{playername}:{msgcolour} {msg}'
  # NATION channel types.
  nation: '{channelTag}{nationformatted}{townformatted}{playername}:{msgcolour} {msg}'
  # ALLIANCE channel types.
  alliance: ' {channelTag}{nationformatted}{townformatted}{playername}:{msgcolour} {msg}'
  # DEFAULT channel types.
  default: '{channelTag} {permprefix}{playername}{permsuffix}&f:{msgcolour} {msg}'
 
tag_formats:
  world: '[%s] '
  town: '[%s] '
  nation: '[%s] '
  # First %s is the nation tag, second is the town tag.
  # You may also use %t for the town tag and %n for the nation tag!
  both: '&f[&6%s&f|&3%s&f] '
 
colour:
  king: '&6'
  mayor: '&b'
  resident: '&f'
  nomad: '&f'
 
modify_chat:
  # When true Towny will format all ChannelTypes,
  # When false Towny will only format TOWN, NATION, ALLIANCE, DEFAULT types.
  # When false Towny will not format GLOBAL types, leaving other chat plugins to do the work.
  enable: 'true'
  # If true the chat formats will be read from below to allow per world formatting.
  # These can then be altered individually.
  per_world: 'false'
  # If true any player who speaks in a channel in which he cannot be heard,
  # either by being along in the channel or out-of-range of another player in his chat channel,
  # that player will see a message saying they cannot be heard.
  alone_message: 'false'
  # This allows you to set your alone message.
  alone_message_string: No one in range can hear you or you are alone in this channel.
 
# If true players will see [Towny] Modes set: general when they log in.
display_modes_set_on_join: 'true'
```

**channels.yml**
```
Channels:
    general:
        commands: [g]
        type: GLOBAL
        channeltag: '&2'
        messagecolour: '&f'
        permission: 'towny.chat.general'
        default: true
        range: '0'
        spam_time: '0.5'
        
    town:
        commands: [tc]
        type: TOWN
        channeltag: '&b'
        messagecolour: '&b'
        permission: 'towny.chat.town'
        range: '0'
        spam_time: '0.5'
         
    nation:
        commands: [nc]
        type: NATION
        channeltag: '&e'
        messagecolour: '&e'
        permission: 'towny.chat.nation'
        range: '0'
        spam_time: '0.5'

    alliance:
        commands: [ac]
        type: ALLIANCE
        channeltag: '&3'
        messagecolour: '&a'
        permission: 'towny.chat.alliance'
        range: '0'
        spam_time: '0.5'

    admin:
        commands: [a,admin]
        type: DEFAULT
        channeltag: '&f[&4ADMIN&f]'
        messagecolour: '&c'
        permission: 'towny.chat.admin'
        range: '-1'
        
    mod:
        commands: [m,mod]
        type: DEFAULT
        channeltag: '&f[&9MOD&f]'
        messagecolour: '&5'
        permission: 'towny.chat.mod'
        range: '-1'
        
    local:
        commands: [l,lc]
        type: GLOBAL
        channeltag: '&5'
        messagecolour: '&f'
        permission: 'towny.chat.local'
        range: '100'

```
