### DISCUSSION TITLE
Color codes in town names?

### DISCUSSION THREAD

**Discussion by CuboidCat** [TownyAdvanced/Towny#5719] [Q&A] [answered]
Hey, so I've been trying for a while to allow people to use & color codes in their town names so people can have different colored names. I know it is possible because another server I play on has this enabled. When I try and make a town name with a & code it says invalid. So how would I go about enabling this?

**Comment by LlmDl** [comment]
The [regex](https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#towny-regex-settings) needs to have & added to the name_check_regex.

**Reply by CuboidCat** [reply]
I did that and it still says invalid name


  # Regex fields used in validating inputs.
  regex:
    name_filter_regex: '[\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._\[\]-]*$&
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'

**Reply by LlmDl** [reply]
```
  regex:
    name_filter_regex: '[\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._\&\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'
```
Try it like this

**Reply by CuboidCat** [reply]
Now it is saying no names are valid. Not even ones without the symbols.

**Reply by LlmDl** [reply]
You'll have to show me what you have in your regex.

**Reply by CuboidCat** [reply]
Just what you sent me.


  regex:
    name_filter_regex: '[\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._\&\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'

**Reply by LlmDl** [reply]
Maybe show me your whole config.

**Reply by CuboidCat** [reply]
Would you like me to send the config.yml?

**Reply by LlmDl** [reply]
Actually I've spotted it, in between cutting and pasting we lost some of teh \\'s in the first regex

```
  regex:
    name_filter_regex: '[\\\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._\&\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'
```

**Reply by CuboidCat** [reply]
```
  # Regex fields used in validating inputs.
  regex:
    name_filter_regex: '[\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._\&\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'
```

**Reply by LlmDl** [reply]
Replace your name_filter_regex with the one in my post above.

**Reply by CuboidCat** [reply]
still is saying all the names are invalid.
```
  regex:
    name_filter_regex: '[\\\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._\&\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'
```

**Reply by LlmDl** [reply]
Maybe try 
```
  regex:
    name_filter_regex: '[\\\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._&\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'
```

**Reply by CuboidCat** [reply]
I'll try it when I get back. Thanks for your help.

**Comment by CuboidCat** [comment, marked as answer]
Setting the regex to this has fixed the issue.
```
  regex:
    name_filter_regex: '[\\\/]'
    name_check_regex: ^[\p{L}a-zA-Z0-9._&\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9 \s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^\P{M}a-zA-Z0-9\&._\[\]-]'
```
