### DISCUSSION TITLE
Issue with townychat channel tags

### DISCUSSION THREAD

**Discussion by dragontekgaming** [TownyAdvanced/Towny#5817] [Q&A]
I added a channel [Trade], which works fine, but can't seem to get the "local" channel tag to change. In fact, none of the channel tags, except for trade and general work. All others are default. Also noticed, Trade channel msgcolor is teal, not yellow.
```
Channels:
    general:
        commands: [g]
        type: GLOBAL
        channeltag: '_'
        messagecolour: '&f'
        permission: 'towny.chat.general'
        default: true
        range: '-1'
        spam_time: '0.5'
        
    town:
        commands: [tc]
        type: TOWN
        channeltag: '&8[&3TC&8]'
        messagecolour: '&b'
        permission: 'towny.chat.town'
        range: '-1'
        spam_time: '0.5'
         
    nation:
        commands: [nc]
        type: NATION
        channeltag: '&8[&6NC&8]'
        messagecolour: '&e'
        permission: 'towny.chat.nation'
        range: '-1'
        spam_time: '0.5'

    alliance:
        commands: [ac]
        type: ALLIANCE
        channeltag: '&8[&2AC&8]'
        messagecolour: '&a'
        permission: 'towny.chat.alliance'
        range: '-1'
        spam_time: '0.5'

    admin:
        commands: [a,admin]
        type: DEFAULT
        channeltag: '&f[&4ADMIN&f]'
        messagecolour: '&c'
        permission: 'towny.chat.admin'
        range: '-1'
        
    mod:
        commands: [m,mod]
        type: DEFAULT
        channeltag: '&f[&9MOD&f]'
        messagecolour: '&b'
        permission: 'towny.chat.mod'
        range: '-1'
        
    local:
        commands: [l,lc]
        type: GLOBAL
        channeltag: '&8[&7LC&8]'
        messagecolour: '&7'
        permission: 'towny.chat.local'
        range: '100'
    trade:
        commands: [tsc,trades]
        type: GLOBAL
        channeltag: '&8[&6TRADE&8]'
        messagecolour: '&3'
        permission: 'towny.chat.trade'
        range: '-1'
        spam_time: '60'
```
