### DISCUSSION TITLE
/town spawn problem

### DISCUSSION THREAD

**Discussion by PikaCrew** [TownyAdvanced/Towny#6118] [Q&A] [answered]
/town spawn (name) asks for confirmation. On confirmation, it takes the cost but doesn't teleport players.

```
############################################################
# +------------------------------------------------------+ #
# |                Global town settings                  | #
# +------------------------------------------------------+ #
############################################################
  
global_town_settings:
  
  # Players within their town or allied towns will regenerate half a heart after every health_regen_speed seconds.
  health_regen:
    speed: 3s
    enable: 'true'
  
  # Allow towns to claim outposts (a townblock not connected to town).
  allow_outposts: 'true'
  
  # When set to true outposts can be limited by the townOutpostLimit value of the Town Levels and
  # the nationBonusOutpostLimit value in the Nation Levels. In this way nations can be made to be
  # the only way of receiving outposts, or as an incentive to receive more outposts. Towns which are
  # larger can have more outposts.
  # When activated, this setting will not cause towns who already have higher than their limit
  # to lose outposts. They will not be able to start new outposts until they have unclaimed outposts
  # to become under their limit. Likewise, towns that join a nation and receive bonus outposts will
  # be over their limit if they leave the nation.
  limit_outposts_using_town_and_nation_levels: 'false'
  
  # When limit_outposts_using_town_and_nation_levels is also true, towns which are over their outpost
  # limit will not be able to use their /town outpost teleports for the outpost #'s higher than their limit,
  # until they have dropped below their limit.
  # eg: If their limit is 3 then they cannot use /t outpost 4
  over_outpost_limits_stops_teleports: 'false'
  
  # Allow the use of /town spawn
  # Valid values are: true, false, war, peace
  # When war or peace is set, it is only possible to teleport to the town,
  # when there is a war or peace.
  allow_town_spawn: 'true'
  
  # Allow regular residents to use /town spawn [town] (TP to other towns if they are public).
  # Valid values are: true, false, war, peace
  # When war or peace is set, it is only possible to teleport to the town,
  # when there is a war or peace.
  allow_town_spawn_travel: 'true'
  
  # Allow regular residents to use /town spawn [town] to other towns in your nation.
  # Valid values are: true, false, war, peace
  # When war or peace is set, it is only possible to teleport to the town,
  # when there is a war or peace.
  allow_town_spawn_travel_nation: 'true'
  
  # Allow regular residents to use /town spawn [town] to other towns in a nation allied with your nation.
  # Valid values are: true, false, war, peace
  # When war or peace is set, it is only possible to teleport to the town,
  # when there is a war or peace.
  allow_town_spawn_travel_ally: 'true'
  
  # When set to true both nation and ally spawn travel will also require the target town to have their status set to public.
  is_nation_ally_spawning_requiring_public_status: 'false'
  
  # If non zero it delays any spawn request by x seconds.
  teleport_warmup_time: '1'
  
  # When set to true, if players are currently in a spawn warmup, moving will cancel their spawn.
  movement_cancels_spawn_warmup: 'false'
  
  # When set to true, if players are damaged in any way while in a spawn warmup, their spawning will be cancelled.
  damage_cancels_spawn_warmup: 'false'
  
  # Number of seconds that must pass before a player can use /t spawn or /res spawn.
  spawn_cooldown_time: '30'
  
  # Decides whether confirmations should appear if you spawn to an area with an associated cost.
  spawn_warnings: 'true'
  
  # Number of seconds that must pass before pvp can be toggled by a town.
  # Applies to residents of the town using /res toggle pvp, as well as
  # plots having their PVP toggled using /plot toggle pvp.
  pvp_cooldown_time: '30'
  
  # Number of seconds that must pass before peacfulness can be toggled by a town or nation.
  peaceful_cooldown_time: '30'
  
  # When true Towny will handle respawning, with town or resident spawns.
  town_respawn: 'false'
  ```
