### DISCUSSION TITLE
townychat startup error

### DISCUSSION THREAD

**Discussion by mituba3328** [TownyAdvanced/Towny#6994] [Q&A] [answered]
A java error occurs when Towny Chat starts
Also, perhaps due to this, Towny commands cannot be executed.

towny version
0.99.5.18 (I tried the latest version to resolve the issue)
townychat version
0.109
serverlog
https://pastebin.com/0ENda55W
ChatConfig.yml
https://pastebin.com/iFky34Q4
towny config.yml
https://pastebin.com/3LynPWeu
townyperms.yml
https://pastebin.com/qLUg16EP

problem log

`[22:03:52] [Server thread/INFO]: [Towny] Enabling Towny v0.99.5.18
[22:03:52] [Server thread/INFO]: ====================      Towny      ========================
[22:03:52] [Server thread/ERROR]: Error occurred while enabling Towny v0.99.5.18 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.logging.Logger.warning(String)" because "this.logger" is null
	at com.palmergames.bukkit.config.CommentedConfiguration.loadFile(CommentedConfiguration.java:77) ~[?:?]
	at com.palmergames.bukkit.config.CommentedConfiguration.load(CommentedConfiguration.java:69) ~[?:?]
	at com.palmergames.bukkit.towny.Towny.handleLegacyConfigs(Towny.java:336) ~[?:?]
	at com.palmergames.bukkit.towny.Towny.loadFoundation(Towny.java:222) ~[?:?]
	at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:139) ~[?:?]`

I knew it was a permission setting, but I couldn't solve it on my own.
I also tried updating the towny and townychat jar files to the latest ones, deleting ChatConfig.yml and Channels.yml and starting.

Also, since I can't speak English, I use a translation tool (I'm Japanese)

**Comment by LlmDl** [comment, marked as answer]
I pasted your config.yml into https://yaml-online-parser.appspot.com and it shows that you've broken the yaml formatting by using a tab or by mis-aligning the spacing.

If you fix your config.yml TownyChat will be happier.

**Reply by LlmDl** [reply]
It looks like you pasted a block of text into the config:

```
  # Maximum distance between homeblocks.
  # This will forc  resource_nether:
    spawn-on-respawn: true
    world: world
    x: 0.5333023763467399
    y: 66.0
    z: 0.4862432775534738
    yaw: -175.01181
    pitch: 25.201715
  world_the_end:
    spawn-on-respawn: true
    world: world
    x: 0.5333023763467399
    y: 66.0
    z: 0.4862432775534738
    yaw: -175.01181
    pitch: 25.201715
```
