### ISSUE TITLE
Towns revert to normal after disband

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#1193]
Originally reported on Google Code with ID 1164

```
What steps will reproduce the problem?
1. Town falls into ruin due to lack of funds
2. Towns land becomes unclaimed by the server
3. The terrain that the town owned slowly regenerates the map from before the town
started.

What is the expected output? What do you see instead?

I have the setting disabled, I think (meaning I want it to NOT get rid of structures
just unclaim land). See config below where I believe it should be disabled.

What is your towny build?

Towny 0.80.1.0 for CB 1.2.5-R4.0

What is your bukkit build?

CB 1.2.5-R4.0

What operating system?

It's on a VPS.

Please use pastebin.com to attach links to relevant files which could
include:
- Your full server startup from server.log,
- Your towny config.yml,
- Your permissions file,
- Broken towny data files that prevent towny from loading on startup.

Config.yml:

  # World management settings to deal with un/claiming plots
  plot_management:

    block_delete:
      enabled: 'false'
      # These items will be deleted upon a plot being unclaimed
      unclaim_delete: 26,50,55,63,64,68,70,71,72,75,76,93,94

    mayor_plotblock_delete:
      enabled: 'false'
      # These items will be deleted upon a mayor using /plot clear
      # To disable deleting replace the current entries with NONE.
      mayor_plot_delete: WALL_SIGN,SIGN_POST

    revert_on_unclaim:
      # *** WARNING***
      # If this is enabled any town plots which become unclaimed will
      # slowly be reverted to a snapshot taken before the plot was claimed.
      #
      # Regeneration will only work if the plot was
      # claimed under version 0.76.2, or
      # later with this feature enabled
      #
      # If you allow players to break/build in the wild the snapshot will
      # include any changes made before the plot was claimed.
      enabled: 'false'
      speed: 1s
      # These block types will NOT be regenerated
      block_ignore: 14,21,22,41,42,48,50,52,56,57,63,68,89

    wild_revert_on_mob_explosion:
      # Enabling this will slowly regenerate holes created in the
      # wilderness by monsters exploding.
      enabled: 'true'
      entities: Creeper,EnderCrystal,EnderDragon,Fireball,SmallFireball,TNTPrimed
      delay: 20s

I can get a start up log too if you need it.



```

Reported by `gobadgers77@live.com` on 2012-07-02 02:11:53
