### ISSUE TITLE
towny

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#1807]
Originally reported on Google Code with ID 1781

```
i cant make towns thats it...it says i dont have enough money to settle in a new town...
all the prices are at 0.0...
town:
    new_expand:
    # How much it costs to start a nation.
    price_new_nation: '0.0'
    # How much it costs to start a town.
    price_new_town: '0.0'
    # How much it costs to make an outpost. An outpost isn't limited to being on the
edge of town.
    price_outpost: '0.0'
    # The price for a town to expand one townblock.
    price_claim_townblock: '0.0'
    # How much it costs a player to buy extra blocks.
    price_purchased_bonus_townblock: '0.0' 
```

Reported by `hungryXXham` on 2013-07-09 05:41:34
