### ISSUE TITLE
TownyChat Alias leave/join

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#1927]
Originally reported on Google Code with ID 1902

```
Add an alias ability as /leave and /join and taken by many plugins.


      leave:
         aliases: [chleave] <-----------NEW ALIAS
        description: Leaves a channel
        usage: /leave channel
        permission: Requires a permissions per channel to use - towny.chat.leave.{channelname}

      join:
        aliases: [chjoin] <-------------NEW ALIAS
        description: Joins a channel
        usage: /join channel
        permission: Requires a permissions per channel to use - towny.chat.join.{channelname}
```

Reported by `rasnyderiii` on 2013-11-22 16:15:56
