### ISSUE TITLE
No tips on how to format the notifications

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#2039]
Originally reported on Google Code with ID 2016

```
Hello, Under 

############################################################
# +------------------------------------------------------+ #
# |                 Town Notifications                   | #
# +------------------------------------------------------+ #
############################################################

It says 

# This is the format for the notifications sent as players move between plots.
# Empty a particular format for it to be ignored.

# Example:
#[notification.format]
# ~ [notification.area_[wilderness/town]][notification.splitter][notification.[no_]owner][notification.splitter][notification.plot.format]
# ... [notification.plot.format]
# ... [notification.plot.homeblock][notification.plot.splitter][notification.plot.forsale][notification.plot.splitter][notification.plot.type]
# ~ Wak Town - Lord Jebus - [Home] [For Sale: 50 Beli] [Shop]

Now, I was wondering, How can I use these [node.random] bracket thingies to format
the order of the notifications? Is that even possible? Cause I don't see a spot where
I could put that code. Any help?¨

Not to be confused by this, Which I already have planned out:

notification:
  format: '&8» %s'
  splitter: '&8 ∙ '
  area_wilderness: '&2%s'
  area_wilderness_pvp: '&6PvP'
  area_town: '&6%s'
  area_town_pvp: '&6PvP'
  owner: '&a%s'
  no_owner: '&a%s'
  plot:
    splitter: ' '
    format: '%s'
    homeblock: '&6Spawn Block'
    outpostblock: '&eOutpost'
    forsale: '&e[For Sale: %s]'
    type: '&6[%s]'
```

Reported by `enitoni` on 2014-04-10 20:17:46
