### ISSUE TITLE
Problems with War Event

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#2146]
Originally reported on Google Code with ID 2123

```
Hi, I use your plugin since 1 years and with the last version 0.88.0.0_(1.6.4), I find
some bugs that were not there before. The fist problem,(the most important),is the
neutrality don't work, in fact during the war, pvp is forced even in towns of neutral
nations. The second problem is that the values: point_town and point_nation; they don't
give points. Thank you for your attention.

I use this setup for the war event:

  ############################################################
  # +------------------------------------------------------+ #
  # |                 War Event settings                   | #
  # +------------------------------------------------------+ #
  ############################################################

  # This is started with /townyadmnin toggle war

  # In peace time War spoils are accumulated from towns and nations being
  # deleted with any money left in the bank.
  #
  # These funds are increased during a war event upon a player death.
  # An additional bonus to the war chest is set in base_spoils.
  #
  # During the event a town losing a townblock pays the wartime_town_block_loss_price
to the attacking town.
  # The war is won when the only nations left in the battle are allies, or only a single
nation.
  #
  # The winning nations share half of the war spoils.
  # The remaining half is paid to the town which took the most town blocks, and lost
the least.

  event:
    warning_delay: '30'
    #If false all towns not in nations can be attacked during a war event.
    towns_are_neutral: 'true'

    # If true and the monarch/king dies the nation is removed from the war.
    remove_on_monarch_death: 'false'
    # If enabled players will be able to break/place blocks in enemy plots during a
war.
    allow_block_griefing: 'true'

    # A townblock takes damage every 5 seconds that an enemy is stood in it.
    block_hp:
      town_block_hp: '60'
      home_block_hp: '80'

    eco:
      # This amount is new money injected into the economy with a war event.
      base_spoils: '0.0'
      # This amount is taken from the losing town for each plot lost.
      wartime_town_block_loss_price: '100.0'
      # This amount is taken from the player if they die during the event
      price_death_wartime: '100.0'

    points:
      points_townblock: '5'
      points_town: '10'
      points_nation: '100'
      points_kill: '1'

    # The minimum height at which a player must stand to count as an attacker.
    min_height: '60'

```

Reported by `ServerOverLordItalia` on 2014-07-27 03:39:53
