### ISSUE TITLE
Question: Edit L chat

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3132]
How do I specifically edit local chat? It appears I can only edit global, nations, towns, and defaults. I only want to edit the format of local chat.

**Comment by LlmDl** [comment]
You need to look at the type that local is set to, by default it is in the channels.yml like this:
```
    local:
        commands: [l,lc]
        type: GLOBAL
        channeltag: '&f[local]'
        messagecolour: '&f'
        permission: 'towny.chat.local'
        craftIRCTag: 'admin'
        range: '100'
```
Since it is set to type: GLOBAL, whatever you set your global channel_format in the chatconfig.yml to will be used to format local chat.
