### ISSUE TITLE
Question: Towny names regex

### ISSUE THREAD

**Issue by AfkF24** [TownyAdvanced/Towny#3429]
**Ask your question as best as you are able:** Hey, I was trying to go through some docs to figure out how I can limit the characters used for town names, but had no luck. To shorten things up, I am trying to limit town names to only be able to contain [A-Za-z0-9_] characters. Is there a way for me to do this?

I have also stumbled upon an issue where certain characters sometimes aren't displayed in chat - for example when a town is named `_Town_` (with underscores). It displays the name in chat correctly, but when entering their land, it displays the name without underscores. Can I somehow change this behavior?

I have found a regex section within the config, but it is unclear to me which regex I should be editing to achieve this and how.
```
  regex:
    name_filter_regex: '[ /]'
    name_check_regex: ^[a-zA-Z0-9._\[\]-]*$
    string_check_regex: ^[a-zA-Z0-9\s._\[\]\#\?\!\@\$\%\^\&\*\-\,\*\(\)\{\}]*$
    name_remove_regex: '[^a-zA-Z0-9._\[\]-]'
```

Thanks!
