### ISSUE TITLE
Defect: Evil switch users

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#343]
Originally reported on Google Code with ID 307

```
Below is a part of my config which i have set up and somehow people who arent in a specific
town can go in and use switches etc and im not sure why, please help as its vital for
the town's security

    town:
        ally:
            destroy: 'false'
            item_use: 'false'
            switch: 'false'
            build: 'false'
        outsider:
            destroy: 'false'
            item_use: 'false'
            switch: 'false'
            build: 'false'
        resident:
            destroy: 'false'
            item_use: 'false'
            switch: 'true'
            build: 'false'

    switch_ids: 25,54,61,62,64,69,70,71,71,77,96,84,93,94

    item_use_ids: 259,325,326,327,351



```

Reported by `RossJGosling` on 2011-09-26 16:43:04
