### ISSUE TITLE
Suggestion: Kick inactive players from town

### ISSUE THREAD

**Issue by Darkweasam** [TownyAdvanced/Towny#3656]
**Please explain your feature request to the best of your abilities:**
Hello,

Most of my town mayors are fed up with having inactive players in their town, it is literally impossible to track who is active and who is not above 50+ players towns.
I would like to request a feature for the config.yml where I can set a day count that kicks inactive players from town

InactivePlayerKick: 30
This would kick players on each "new day" if they been inactive for over 30days in the town (new day: same time when the taxes are deducted from towns, once per 24h)

**Comment by LlmDl** [comment]
Towny has an old-resident-deletion feature already.

```
  # if enabled old residents will be deleted, losing their town, townblocks, friends
  # after Two months (default) of not logging in
  delete_old_residents:
    enable: 'false'
    deleted_after_time: 60d
    delete_economy_account: 'true'
    # When true only residents who have no town will be deleted.
    delete_only_townless: 'false'
```
Set the enable to true and set the delete_after_timer: 30d
