### ISSUE TITLE
Permission for accept nation invites

### ISSUE THREAD

**Issue by Federico2806** [TownyAdvanced/Towny#3753]
There isn't a single permission to accept the nation invites, if you have towny.command.town.* you can accept invites, but if you have all towny.command.town permission except towny.command.town.* you can't and the server will tell you that you haven't permissions.

This is my townyperms config, and i can't accept nation invites

```
towns:
    default:
        - towny.command.resident.otherresident
        - towny.command.resident.friend
        - towny.command.town.list
        - towny.command.town.online
        - towny.command.town.leave
        - towny.command.town.reslist
        - towny.command.town.othertown
        - towny.command.towny.top
        - towny.command.nation.list
        - towny.command.nation.othernation
        - towny.chat.town
        - towny.chat.general
    mayor:
        - towny.command.town.rank.*
        - towny.command.town.mayor
        - towny.command.town.set.board
        - towny.command.town.set.mayor
        - towny.command.town.set.name
        - towny.command.town.say
        - towny.command.town.delete
        - towny.command.town.add
        - towny.command.town.kick
        - towny.command.nation.join
        - towny.command.nation.leave
        - towny.command.nation.new
        - towny.command.town.outlaw

    ranks:
        Sindaca:
            - towny.command.town.mayor
            - towny.command.town.rank.ViceSindaco
            - towny.command.town.set.board
            - towny.command.town.set.name
            - towny.command.town.say
            - towny.command.town.add
            - towny.command.town.kick
            - towny.command.nation.join
            - towny.command.town.outlaw
        ViceSindaco:
            - towny.command.town.rank.default
            - towny.command.town.add
            - towny.command.town.kick
            - towny.command.town.say
            - towny.command.town.outlaw
```
