### ISSUE TITLE
Question: Disable abilities for Mayor to build, destroy, item_use, switch in residents plots

### ISSUE THREAD

**Issue by AdrienFd** [TownyAdvanced/Towny#3914]
I would like to know if there is a way (or you could be added.) to disable the abilities the mayors have over residents plots ? 

Right now they can build, destroy, use chests, doors in residents owned plots and that's kind of a big deal, on my server some mayor can be trust some other not ... 

I checked the permissions that the mayors have I found nothing about these abilities being write in the townyperm file, so I tried removing all the actual perms for the mayor and still mayor can do everything they want in residents plots of their town. 

I know the modifications I made to the perm file were working because command like town claim, plot management weren't working as expected but still mayor can break blocks and open chest in residents plots.

Thank you.

**Comment by LlmDl** [comment]
In the townyperms.yml:
mayors have towny.claimed.owntown.* 
you want to change it to towny.claimed.townowned.*

**Comment by AdrienFd** [comment]
Yeah that's what i read from the documentation however none of these perms were in the townyperm.yml ... I'm assuming the fact mayors can build, destroy is weird !
This is was my permission file : 
```# This file contains custom permission sets which will be assigned to your players

# The 'nomad' permission set covers players not in any town
nomad:
    - towny.command.towny.map
    - towny.command.towny.prices
    - towny.command.towny.tree
    - towny.command.towny.time
    - towny.command.towny.universe
    - towny.command.town.online
    - towny.command.town.here
    - towny.command.town.new
    - towny.command.town.join
    - towny.command.town.list
    - towny.command.plot.perm
    - towny.town.resident
    - towny.town.spawn.public
    - towny.chat.general
# This section of permissions covers players who are members of a town.
towns:
    default:
        # 'default' is the permission set which is auto assigned to any normal town member
        - towny.command.resident.*
        - towny.command.plot.claim
        - towny.command.plot.unclaim
        - towny.command.plot.forsale
        - towny.command.plot.notforsale
        - towny.command.plot.toggle.fire
        - towny.command.plot.toggle.mobs
        - towny.command.plot.set.perm
        - towny.command.plot.set.reset
        - towny.command.town.online
        - towny.command.town.leave
        - towny.command.town.deposit
        - towny.town.spawn.town
        - towny.chat.town
    mayor:
        # Mayors get these permissions in addition to the default set.
        - towny.tax_exempt
        - towny.command.towny.top
        - towny.command.town.here
        - towny.command.town.list
        - towny.command.town.leave
        - towny.command.town.withdraw
        - towny.command.town.deposit
        - towny.command.town.rank.*
        - towny.command.town.reslist
        - towny.command.town.outlaw
        - towny.command.town.outpost.list
        - towny.command.town.set.*
        - towny.command.town.buy
        - towny.command.town.othertown
        - towny.command.town.say
        - towny.command.town.toggle.open
        - towny.command.town.toggle.public
        - towny.command.town.toggle.jail
        - towny.command.town.delete
        - towny.command.town.add
        - towny.command.town.kick
        - towny.command.town.claim.*
        - towny.command.town.unclaim
        - towny.command.town.online
        - towny.command.town.invite.*
        - towny.command.plot.*
        - towny.command.town.plots
        - towny.command.town.mayor
        - towny.outlaw.jailer
    ranks:
        # Ranks contain additional permissions residents will be
        # granted if they are assigned that specific rank.
        assistant:
            - towny.tax_exempt
            - towny.command.town.claim.*
            - towny.command.town.invite.add
            - towny.command.plot.*
            - towny.command.town.toggle.public
            - towny.claimed.owntown.switch.*
            # assistants are able to grant VIP and helper rank
            - towny.command.town.rank.vip
            - towny.command.town.rank.helper
            - towny.outlaw.jailer
        helper:
            - towny.claimed.townowned.switch.*
        builder:
            - towny.claimed.townowned.*
        donator:
            # Currently only an example rank holder with no extra permissions
        vip:
            # Currently only an example rank holder with no extra permissions
            # Sheriff rank is able to jail other town members.
        sheriff:
            - towny.command.town.toggle.jail
            - towny.outlaw.jailer
```

So i tried to reinstall it, I saw the towny.claimed.owntown.* perm and changed it to towny.claimed.townowned.* and add back my config for mysql ... 
But that's still not working mayors can destroy in residents plots, the permission were correctly assigned though :
```
>townyadmin checkperm Mili**** towny.claimed.townowned.*
[12:13:22] [Server thread/INFO]: Permission true
>townyadmin checkperm Mili**** towny.claimed.owntown.*
[12:13:35] [Server thread/INFO]: [Towny] Permission false
>town Amiens
[12:14:21] [Craft Scheduler Thread - 0/INFO]: .oOo.____________.[ Am*** (Village) ].____________.oOo.
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Board: /town set board [msg]
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Founded: Apr 11 2020
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Town Size: 136 / 650 [Bonus: 150]
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Outposts: 2 / 5
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Perm: Build = ---- Destroy = ----
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Perm: Switch = r--- Item = r---
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Explosions: OFF  Firespread: OFF  Mob Spawns: OFF
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Bank: $50.40 | Daily upkeep: 0.0 | Tax: 0.0
[12:14:21] [Craft Scheduler Thread - 0/INFO]: Mayor: Baron Von Mili***
```

Just to be sure, I tried again to reinstall it completely from scratch I only change the perm from towny.claimed.owntown.* to towny.claimed.townowned.* and used the default config, create a brand new town add a resident, plots ... still nothing mayors and residents can do whatever they want ! Seem logic from what I read in the config file so I finally tried to tweak a few things in the config (Default Town/Plot flags) of this fresh install like so : 
```
default_perm_flags:
 
  # Default permission flags for residents plots within a town
  #
  # Can allies/friends/outsiders perform certain actions in the town
  #
  # build - place blocks and other items
  # destroy - break blocks and other items
  # itemuse - use items such as furnaces (as defined in item_use_ids)
  # switch - trigger or activate switches (as defined in switch_ids)
  resident:
    friend:
      build: 'true'
      destroy: 'true'
      item_use: 'true'
      switch: 'true'
    town:
      build: 'false'
      destroy: 'false'
      item_use: 'false'
      switch: 'false'
    ally:
      build: 'false'
      destroy: 'false'
      item_use: 'false'
      switch: 'false'
    outsider:
      build: 'false'
      destroy: 'false'
      item_use: 'false'
      switch: 'false'
 
  # Default permission flags for towns
  # These are copied into the town data file at creation
  #
  # Can allies/outsiders/residents perform certain actions in the town
  #
  # build - place blocks and other items
  # destroy - break blocks and other items
  # itemuse - use items such as flint and steel or buckets (as defined in item_use_ids)
  # switch - trigger or activate switches (as defined in switch_ids)
  town:
    default:
      pvp: 'true'
      fire: 'false'
      explosion: 'false'
      mobs: 'false'
    resident:
      build: 'false'
      destroy: 'false'
      item_use: 'false'
      switch: 'false'
    nation:
      build: 'false'
      destroy: 'false'
      item_use: 'false'
      switch: 'false'
    ally:
      build: 'false'
      destroy: 'false'
      item_use: 'false'
      switch: 'false'
    outsider:
      build: 'false'
      destroy: 'false'
      item_use: 'false'
      switch: 'false'
```
But the mayor can still do whatever they want, on the other side like expected by this latest modification resident can no longer edit town owned plots.

I don't understand were is the problem or what I'm missing, FYI I downloaded the plugin from your git (0.96.1.0) for each new reinstall i tried to elimate any corruption issue. Also by the way I wasn't OP.
