### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by Redd56** [TownyAdvanced/Towny#4079]
in the end some of my players have claims
and for some reason they always have 1 saturation making them unable to eat. why is this and how can i change this

**Comment by LlmDl** [comment]
Towny shouldn't be lowering any saturation. If they are in a town, towny will add to their health and hunger. Are you sure this is Towny?

**Comment by Redd56** [comment]
how do i dissable it doing that

**Comment by Redd56** [comment]
i wasnt saying it was taking it, it was always setting it to half a saturation and full hunger making it impossible to eat

**Comment by Redd56** [comment]
and yes i am sure it doesnt happen without towny and only happens inside borders of townies in the end

**Comment by LlmDl** [comment]
```
global_town_settings:
  # can residents/Allies harm other residents when in an area with pvp enabled? Other than an Arena plot.
  friendly_fire: 'true'
  # Players within their town or allied towns will regenerate half a heart after every health_regen_speed seconds.
  health_regen:
    speed: 3s
    enable: 'true'
```
