### ISSUE TITLE
Suggestion: Clarify Unclaimed_Zone_Switch

### ISSUE THREAD

**Issue by MissPotato** [TownyAdvanced/Towny#4315]
**Please explain your feature request to the best of your abilities:**
"unclaimed_zone_switch" is a bit confusing.  I had to look in discord chat history to figure out what it did. A ton of really good documentation is available in the config file, could a comment be added to this section that clarifies that "unclaimed_zone_switch" correlates to the Switch as defined earlier in the config, maybe just tacked on to the first comment in the wilderness settings section? While in retrospect it is pretty obvious, the distance between these made the connection less obvious in the moment.

**Comment by LlmDl** [comment]
I've actually added new comments/made quite a number of things clearer in teh config which will affect 0.96.2.18 and onwards.

The new wilderness settings config section will look like this:

```
  ############################################################
  # +------------------------------------------------------+ #
  # |                Wilderness settings                   | #
  # +------------------------------------------------------+ #
  ############################################################
 
  # These are default settings only, applied to newly made worlds.
  # They are copied to each worlds data files upon first detection.
  # If you are running Towny for the first time these have been applied
  # to all your already existing worlds.
  # 
  # To make changes for each world edit the settings in the relevant worlds data file 'plugins/Towny/data/worlds/'
 
unclaimed:
  unclaimed_zone_build: 'false'
  unclaimed_zone_destroy: 'false'
  unclaimed_zone_item_use: 'false'
  unclaimed_zone_ignore: SAPLING,GOLD_ORE,IRON_ORE,COAL_ORE,LOG,LEAVES,LAPIS_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,TORCH,DIAMOND_ORE,LADDER,RAILS,REDSTONE_ORE,GLOWING_REDSTONE_ORE,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,LOG_2,VINE,NETHER_WARTS,COCOA
  unclaimed_zone_switch: 'false'
```

How does that look to you?

**Comment by MissPotato** [comment]
This does clarify that it will apply to worlds existing before Towny was added, and is easy to read. I also quite like the stylizations. Though it doesn't explain what the settings do. Such as what "unclaimed_zone_ignore" prevents from happening and the same for "unclaimed_zone_switch".

**Comment by LlmDl** [comment]
What do you think about this:
```
  ############################################################
  # +------------------------------------------------------+ #
  # |                Wilderness settings                   | #
  # +------------------------------------------------------+ #
  ############################################################
  # 
  # These are default settings only, applied to newly made worlds.
  # They are copied to each world's data file upon first detection.
  # If you are running Towny for the first time these have been applied
  # to all your already existing worlds.
  # 
  # To make changes for each world edit the settings in the 
  # relevant worlds data file 'plugins/Towny/data/worlds/'
  # 
  # Furthermore: These settings are only used after Towny has 
  # exhausted testing the player for the towny.wild.* permission nodes.
 
unclaimed:
 
  # Can players build with any block in the wilderness?
  unclaimed_zone_build: 'false'
 
  # Can player destroy any block in the wilderness?
  unclaimed_zone_destroy: 'false'
 
  # Can players use items listed in the above protection.item_use_ids in the wilderness without restriction?
  unclaimed_zone_item_use: 'false'
 
  # Can players interact with switch blocks listed in the above protectection.switch_ids in the wilderness without restriction?
  unclaimed_zone_switch: 'false'
 
  # A list of blocks that will bypass the above settings and do not require the towny.wild.* permission node.
  # These blocks are also used in determining which blocks can be interacted with in Towny Wilds plots in towns.
  unclaimed_zone_ignore: SAPLING,GOLD_ORE,IRON_ORE,COAL_ORE,LOG,LEAVES,LAPIS_ORE,LONG_GRASS,YELLOW_FLOWER,RED_ROSE,BROWN_MUSHROOM,RED_MUSHROOM,TORCH,DIAMOND_ORE,LADDER,RAILS,REDSTONE_ORE,GLOWING_REDSTONE_ORE,CACTUS,CLAY,SUGAR_CANE_BLOCK,PUMPKIN,GLOWSTONE,LOG_2,VINE,NETHER_WARTS,COCOA
```
