### ISSUE TITLE
Suggestion: Expand townychat to format townyranks

### ISSUE THREAD

**Issue by PlopHat** [TownyAdvanced/Towny#4376]
It would be cool if towny could format more ranks (more than the 4 by default: nomad ; king ; mayor ; resident) based on the ranks on townyperms.yml file,

Example (townyperms.yml)
```
towns:
    residents: 
        - some.perms
    mayor:
        - some.perms
    ranks:
        assistant:
            - some.perms
        helper:
            - some.perms
        donator:
            - some.perms
        vip:
            - some.perms
        sheriff:
            - some.perms
nation:
    somenationrank: #Etc to not extend this to much.
```
Townychat config:
```
colour:
  resident: '&f' #fallback in case none applies.
  king: '&6'
  mayor: '&b'
  nomad: '&f'
  sheriff: '&e'
  assistant: '&a'
  ...
  somenationrank: 'somecolor'
```

i don't know if i made the idea clear, but it would be cool if it could be made.
Thanks for reading!

Edit: typo
