### ISSUE TITLE
Suggestion: Allow Town Ruins to persist indefinitely.

### ISSUE THREAD

**Issue by DaniGTA** [TownyAdvanced/Towny#4970]
In the current settings of Towny it is only possible to set the disappearance of ruins, only in hours. I would not want to let the ruins disappear on my server so that even after a long time the name of the city stands.

An option to disable the disappearance of ruins I would like to see here.

**Comment by LlmDl** [comment]
I think you're talking about the revert-on-unclaim feature.

The install guide explains how to disable this: `/tw toggle revertunclaim` (used in every world.)

**Comment by DaniGTA** [comment]
```
town_ruining:
  town_ruins:
 
    # If this is true, then if a town falls, it remains in a 'ruined' state for a time.
    # In this state, the town cannot be claimed, but can be looted.
    # The feature prevents mayors from escaping attack/occupation, 
    # by deleting then quickly recreating their town.
    enabled: 'true'
 
    # This value determines the maximum duration in which a town can lie in ruins
    # After this time is reached, the town will be completely deleted.
    # Does not accept values greater than 1000.
    max_duration_hours: '1000' 
   ```
   Thats what i dont want. I would like to completly prevent a automatic deletion of a ruin.
   
   And in the install guide i didnt find the explaination.
