### ISSUE TITLE
Suggestion: Move MySQL config into separate file

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5175]
Currently, the MySQL config is located directly in `config.yml`.  This is probably fine for most servers;  but for any server using version control, especially if that VCS is public, having MySQL inside `config.yml` makes it tricky to use MySQL safely.

I would like to suggest moving the MySQL config into a separate file, which users can then `.gitignore`.  This would allow VCS management of the rest of Towny, without risking exposing sensitive information about the database (like passwords).

The settings that should be moved:
```
    # SQL database connection details (IF set to use SQL).
    sql:
      hostname: localhost
      hostname: localhost
      port: '3306'
      dbname: towny
      table_prefix: towny_
      username: towny
      password: ''
      flags: ?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf-8
```
