### ISSUE TITLE
Can't /town claim auto, radius, circle, or rectangle

### ISSUE THREAD

**Issue by roracle** [TownyAdvanced/Towny#5221]
### What steps will reproduce the problem?
1. Be a mayor, no admin perms, just default player settings, nothing fancy.
2. Do the command `/t claim auto` or any of the circle or rect claim commands.
3. "You do not have enough permissions for that command." outputs in chat.
4. Notice nothing was claimed.

Addendum: Normal `/town claim` command works fine.
Addendum2: Doing `/town claim #` says "not registered".

### What is the expected output?
1. For the command to work without error.

### What is your Towny version?
0.97.1.3

### What is your spigot/craftbukkit version?
[01:44:42 INFO]: This server is running Paper version git-Paper-213 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 61a09c5)

1. Your full server startup from the logs\latest.log
https://pastebin.com/bf1LLt4z

2. Your Towny config.yml (if using MySQL please remove password,) :
Default

3. Your townyperms.yml :
Default

4. Your log's error : 
No logged error. Only shows up in the chatbox.

**Comment by LlmDl** [comment]
The default townyperms.yml file doesn't give towny.command.town.claim.multiple to mayors.

**Comment by roracle** [comment]
Ugh, I just tried the fix:
Still get the error. I did try giving my mayors `towny.command.town.claim.*` last night and it didn't work, and I just tried to specify it with your response, and it still does not work. :(

**Comment by LlmDl** [comment]
As per the plugin.yml:
```
    towny.command.town.claim.*:
        description: User can access all town claim related commands.
        default: false
        children:
            towny.command.town.claim.town: true
            towny.command.town.claim.outpost: true
            towny.command.town.claim.town.multiple: false
```

the multiple node is not a child node of towny.command.town.claim.*. Give the proper node and it works just fine.
