### ISSUE TITLE
Suggestion:  Command blacklist that excludes non-Town and non-Personally-Owned places but includes the wilderness.

### ISSUE THREAD

**Issue by TKwSni** [TownyAdvanced/Towny#5279]
**Please explain your feature request to the best of your abilities:**

Right now the ability to blacklist commands is great but, for example if you have an embassy in a town you dont belong to, you will be forced to use /t spawn and walk to your embassy, if you have the sethome command blacklisted. It would be great that:

You could be able to bypass the blacklist if you are in a plot you own
Mayors whitelist players to use command in their town
Mayor could disable the blacklist in their town
Players could whitelist commands to his friends in their plot

**Comment by LlmDl** [comment]
The point about not being able to run commands in a plot you own is avoided by using the personally-owned blacklist:
```
    # This allows the usage of blacklisted commands only in plots personally-owned by the player.
    # Players with the towny.claimed.townowned.* permission node will be able to run these commands
    # inside of town-owned land. This would include mayors, assistants and possibly a builder rank.
    # Players with the towny.claimed.owntown.* permission node (given to mayors/assistants usually,)
    # will also not be limited by this command blacklist.
    # Commands have to be on town_command_blacklisting.town_blacklisted_commands, else this is not going to be checked.
    player_owned_plot_limited_commands: sethome,home
```
which should bypass the blacklist in town-owned plots.

**Comment by TKwSni** [comment]
For town owned plots, I have to give them the permission node right?   towny.claimed.townowned.*  for players which own a plot in a town where they arent resident, and then adding the commands I dont want to block from the blacklist exactly as your example, but it is not working for me. what am I doing wrong ?

**Comment by LlmDl** [comment]
I'm not speaking about the town-owned-only blacklist, The list I show above is for plots a player personally owns.

**Comment by TKwSni** [comment]
Yes sorry I didnt mean that, I mean like an embassy right? so how should I setup this to bypass the blacklist?

Is there a permission node I need to add somwhere?
```

  town_command_blacklisting:
 
    # Allows blocking commands inside towns through the town_blacklisted_commands setting.
    # This boolean allows you to disable this feature altogether if you don't need it
    enabled: 'true'
 
    # Comma separated list of commands which cannot be run inside of any town.
    town_blacklisted_commands: sethome, home
 
    # This allows the usage of blacklisted commands only in plots personally-owned by the player.
    # Players with the towny.claimed.townowned.* permission node will be able to run these commands
    # inside of town-owned land. This would include mayors, assistants and possibly a builder rank.
    # Players with the towny.claimed.owntown.* permission node (given to mayors/assistants usually,)
    # will also not be limited by this command blacklist.
    # Commands have to be on town_command_blacklisting.town_blacklisted_commands, else this is not going to be checked.
    player_owned_plot_limited_commands: sethome, home
 
    # This allows the usage of blacklisted commands only in the player's town 
    # and the wilderness (essentially blocking commands from being ran by tourists/visitors)
    # Players with the towny.globally_welcome permission node are not going to be limited by this list.
    # Commands have to be on town_command_blacklisting.town_blacklisted_commands, else this is not going to be checked.
    own_town_and_wilderness_limited_commands: []
```
