### ISSUE TITLE
Enemy towns can access chests during war

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5290]
### What steps will reproduce the problem?
1. toggle war event on

### What is the expected output?
Outsiders shouldnt be able to access chests.

### What is your Towny version?
Towny 0.97.1.9

### What is your spigot/craftbukkit version?
Tuinity version git-Tuinity-"ac3aee1" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

https://pastebin.com/BPrcC8pY
https://pastebin.com/LYSEQzhp

[latest.log](https://github.com/TownyAdvanced/Towny/files/7190224/latest.log)

**Comment by LlmDl** [comment]
You have switch: true here:
```
  warzone:
 
    # List of materials that can be modified in a warzone.
    # '*' = Allow all materials.
    # Prepend a '-' in front of a material to remove it. Used in conjunction with when you use '*'.
    # Eg: '*,-chest,-furnace'
    editable_materials: tnt,oak_fence,birch_fence,spruce_fence,jungle_fence,dark_oak_fence,acacia_fence,ladder,oak_door,birch_door,spruce_door,jungle_door,dark_oak_door,acacia_fence,iron_door,fire
    item_use: 'true'
    switch: 'true'
```
