### ISSUE TITLE
Question/Problem About Regenerating Land

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#588]
Originally reported on Google Code with ID 552

```
When a mayor unclaims land it starts the return to the state it was before being claimed,
I don't want this to happen but don't know how to stop it.

new_world_settings:
  # force_pvp_on is a global flag and overrides any towns flag setting
  force_pvp_on: 'true'
  # Disable players trampling crops
  disable_player_crop_trampling: 'true'
  # Disable creatures trampling crops
  disable_creature_crop_trampling: 'true'
  # world_monsters_on is a global flag setting per world.
  world_monsters_on: 'true'
  # force_explosions_on is a global flag and overrides any towns flag setting
  force_explosions_on: 'true'
  # force_town_monsters_on is a global flag and overrides any towns flag setting
  force_town_monsters_on: 'true'
  # force_fire_on is a global flag and overrides any towns flag setting
  force_fire_on: 'true'

  # World management settings to deal with un/claiming plots
  plot_management:

    block_delete:
      enabled: 'false'
      # These items will be deleted upon a plot being unclaimed
      unclaim_delete: 50,89

    mayor_plotblock_delete:
      enabled: 'false'
      # These items will be deleted upon a mayor using /plot clear
      # To disable deleting replace the current entries with NONE.
      mayor_plot_delete: WALL_SIGN,SIGN_POST

    revert_on_unclaim: ''
    wild_revert_on_mob_explosion:
      # Enabling this will slowly regenerate holes created in the
      # wilderness by monsters exploding.
      enabled: 'false'
      delay: 5s
```

Reported by `RossJGosling` on 2011-12-20 17:42:29
