### ISSUE TITLE
Suggestion: Allow a maximum amount of a certain plot for people who want to add custom plots within Towny,

### ISSUE THREAD

**Issue by Jqnnies** [TownyAdvanced/Towny#6158]
### **Please explain your feature request to the best of your abilities:**

The idea I've proposed is to add a limit to how many of a certain plot can be in one town. This may be useful for people who want to have one major plot such as a factory building or warp point but don't want people making multiple of them.

**Comment by LlmDl** [comment]
This is possible already using the town_levels townblocktype limits.

**Comment by LlmDl** [comment]
This is done in this fashion to any and all town_levels that you would want to limit:
```
  - numResidents: 1
    debtCapModifier: 1.0
    namePostfix: ' (Settlement)'
    mayorPrefix: 'Hermit '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockTypeLimits:
    - farm: 2
    - arena: 2
    townBlockLimit: 16
    upkeepModifier: 1.0
    townOutpostLimit: 0
```
