### ISSUE TITLE
Hex colors broken in tag and chat formats in TownyChat 0.97

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#6196]
### What steps will reproduce the problem?

1. Use any of these [these](https://github.com/TownyAdvanced/TownyChat/pull/27) hex color formats in the the `tag_formats` and `channel_formats` sections of `ChatConfig.yml`. For example:
```yaml
tag_formats:
  world: '&f[&f%s&f] '
  town: '{#737373}[#91faff%s{&#737373}] '
  nation: '&#737373[&#fac937%s&#737373] '
  # First %s is the nation tag, second is the town tag.
  # You may also use %t for the town tag and %n for the nation tag!
  both: '&8[#6df288%n&8|#91faff%t&8] '
```

2. The hex colours will not be parsed. Here is how `both` looks like in-game:
![image](https://i.gyazo.com/41e1450ae1c2857435f2d105157c80aa.png)

### What is the expected output?

The hex colours are parsed.

### Towny version

0.98.3.11

### Server version

Pufferfish 1.19.2

### Please use Pastebin.com to link the following files

No errors on startup or `/townychat reload`.

Your config.yml: [link](https://hastebin.com/bejaqusoqu.yaml)
Your chatconfig.yml: [link](https://pastebin.com/MZ6sBtrf)
Your channels.yml: [link](https://pastebin.com/bv8DBK32)
