### ISSUE TITLE
Suggestion: Add cost option for outpost & nation spawn teleports

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/Towny#6243]
### **Please explain your feature request to the best of your abilities:**

Seems like teleporting to outpost or nation spawn are lacking cost options. 
They recently got the individual cooldowns, so I think it would be great to give them individual cost options too.
e.g. /t outpost = 50$ or /n spawn = 50$

**Comment by LlmDl** [comment]
Nations do have a /n set spawncost, but there's nothing separating /t outpost from the /t set spawncost yet.

**Comment by Caleston** [comment]
> Nations do have a /n set spawncost, but there's nothing separating /t outpost from the /t set spawncost yet.

Nations do indeed have that, but there is no option to set a default cost, as with /t spawn.
At least on our server we have disabled setting nation/town spawn cost manually, so it would be helpful if we could set a default one for nations as well.

**Comment by Luciusred** [comment]
> > Nations do have a /n set spawncost, but there's nothing separating /t outpost from the /t set spawncost yet.
> 
> Nations do indeed have that, but there is no option to set a default cost, as with /t spawn. At least on our server we have disabled setting nation/town spawn cost manually, so it would be helpful if we could set a default one for nations as well.

u can with essentials create cost for commands and without this option take money for tp on /n or /t spawn/outpost

**Comment by Caleston** [comment]
> > > Nations do have a /n set spawncost, but there's nothing separating /t outpost from the /t set spawncost yet.
> > 
> > 
> > Nations do indeed have that, but there is no option to set a default cost, as with /t spawn. At least on our server we have disabled setting nation/town spawn cost manually, so it would be helpful if we could set a default one for nations as well.
> 
> u can with essentials create cost for commands and without this option take money for tp on /n or /t spawn/outpost

I am already using another plugin to create costs and cooldowns for such commands, but I don't see why those couldn't be built-in to Towny like with other similar commands.

**Comment by PainOchoco** [comment]
What do you guys think of that new config layout for spawn costs:
```yaml
  spawn_travel:
    town:
      # Cost to use /town spawn for residents.
      residents: '0.0'
      # Cost to use '/town outpost [n]' for residents.
      outpost: '0.0'
      # Cost to use '/town spawn [town]' to another town in your nation.
      nation: '5.0'
      # Cost to use '/town spawn [town]' to another town in a nation that is allied with your nation.
      ally: '10.0'
      # Maximum cost to use /town spawn [town] that mayors can set using /t set spawncost.
      # This is paid to the town you goto.
      max: '10.0'

    nation:
      # Cost to use /nation spawn for residents.
      residents: '0.0'
      # Cost to use '/nation spawn [nation]' to another nation that is allied with your nation.
      ally: '10.0'
      # Maximum cost to use /nation spawn [nation] that kings can set using /n set spawncost.
      # This is paid to the nation you goto.
      max: '20.0'
```
