### ISSUE TITLE
Suggestion: TownyWayPointTravel - minor improvements

### ISSUE THREAD

**Issue by NeumimTo** [TownyAdvanced/Towny#6758]
### **Please explain your feature request to the best of your abilities:**

- [x] Being able to whitelist towns twpt mechanics applies to
- [x] Every time a player crosses a town border a notification is sent to a client.
  By default in the notiffication the town name font color is green (at least when it comes to https://javadoc.io/doc/net.md-5/bungeecord-chat/latest/net/md_5/bungee/api/ChatMessageType.html ACTION_BAR type of message).  
  Let admins adjust the text color either globally for twpt towns, or per town
  - Maybe this would be better suggestion to towny itself
- [x] When a player visits a town for the first time add option to specify a command list that will be run as a console command and support use of a placeholder for playername - for example {playername} 
- [ ] Add option for tp cost and tp cooldown
  - And the ability to adjust them via permissions
  
  
  If i would sum it up the final configuration options could look like 
  
  
  ```yml
  whitelist_enabled: true
  whitelist: 
   - very_epic_town:
        discovery_commands:
          - "give {player} minecraft:diamond 64"
          - op {player}
        welcome_message_color: #ffffff
        tp_cooldown: 
            value: 50000 #in millis
            multipliers: 
               - towny.nation.xyz: 1.20
         tp_cost:
           value: 10
           multipliers:
               - towny.nation.xyz: 0
  ```
