### ISSUE TITLE
"/t set perm" does not change permissions in plots with custom TownBlockTypes 

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/Towny#7043]
### What steps will reproduce the problem?

1. Define a custom TownBlockType in the `config.yml`, e.g.

```yaml
  - name: cargo
    cost: 0.0
    tax: 0.0
    mapKey: C
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: ''
```

2. Set a plot in your town to the custom type. `/plot set cargo`.

3. Type `/t set perm ally on`.

4. Turn on `/plot perm hud`.

5. Fly around the town and observe how ally perms are enabled in every plot except the cargo plot.

### What is the expected output?

`/t set perm` changes permissions in plots with custom TownBlockTypes.

### Towny version

0.99.6.3

### Server version

Purpur Build 2062, 1.20.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: [Link](https://mclo.gs/Fb1cekm)
2. Your Towny config.yml: [Link](https://www.toptal.com/developers/hastebin)
3. Your log's error: No error.
