### ISSUE TITLE
Notifications on action-bar doesn't display

### ISSUE THREAD

**Issue by PainOchoco** [TownyAdvanced/Towny#7133]
### What steps will reproduce the problem?

1. Have `notifications_appear_as` set to `action_bar `
2. Walk in a town
3. Notice there is no notification in the action bar

https://github.com/TownyAdvanced/Towny/assets/47084457/3c0d6793-730e-437e-87b5-c6f460bd6e25

### What is the expected output?

The notification should be displayed

### Towny version

0.100.0.12

### Server version

purpur-2094 (1.20.2)

### Please use Pastebin.com to link the following files

```yml
  # This setting controls where chunk notifications are displayed for players.
  # By default, notifications appear in the player's action bar.
  # Available options: action_bar, chat, bossbar, or none.
  notifications_appear_as: action_bar

  # This settings sets the duration the actionbar (The text above the inventory bar) or the bossbar lasts in seconds
  notification_actionbar_duration: "15"
```
