### ISSUE TITLE
daily maintenance of cities/nations

### ISSUE THREAD

**Issue by Mr-Saitam** [TownyAdvanced/Towny#7241]
### What steps will reproduce the problem?

The problem occurs in the collection of daily support

### What is the expected output?

The daily maintenance of cities and nations is charged once a day but after being charged it is charged again within 2 hours.
![image](https://github.com/TownyAdvanced/Towny/assets/81599393/b02c64d1-5fd3-4e37-96a9-e6884f16e146)

### Towny version

 0.100.0.7 

### Server version

1.20.1

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://mclo.gs/LxtC0y5
2. Your Towny config.yml: https://mclo.gs/7EUqqCI
3. Your townyperms.yml: https://mclo.gs/RmUYAkl
4. Your log's error: no error

(optional) If this is to do with permissions,
5. Your permissions file: 

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
What timezone is your server in?

**Comment by Mr-Saitam** [comment]
> ¿En qué zona horaria está tu servidor?
utc

**Comment by LlmDl** [comment]
UTC +0?

**Comment by Mr-Saitam** [comment]
> UTC +0?

yes

**Comment by LlmDl** [comment]
I have tested this with the java timer on/off, and I have tested it with your Time Zone as well. I cannot reproduce the issue you are reporting. No one else is reporting this issue, so it points to something specific about your server.

Are you sure you haven't changed these settings? :

```
  day_timer:
  
    # The time for each "towny day", used for tax and upkeep collection and other daily timers.
    # Default is 24 hours. Cannot be set for greater than 1 day, but can be set lower.
    day_interval: 1d
  
    # The time each "day", when taxes will be collected.
    # Only used when less than day_interval. Default is 12h (midday).
    # If day_interval is set to something like 20m, the new_day_time is not used, day_interval will be used instead.
    new_day_time: 12h
```
    
I know the config you linked has these values but it is acting like you've configured a shorter day interval.
