### ISSUE TITLE
Issue with Towny placeholders & Papi

### ISSUE THREAD

**Issue by Ezals** [TownyAdvanced/Towny#7260]
### What steps will reproduce the problem?

1. Install Towny, TownyChat, Vault, TAB, Papi. Then get the TownyChat extenstion for papi.
2. Use either %townyadvanced_town_tag_override% or %townyadvanced_nation_tag_override% in TAB in the groups.yml section under tabprefix: "" .
3. run the command /papi parse me %townyadvanced_town_tag_override%

### What is the expected output?

Not sure, the TAB admin told me to run it, if it had an error it was towny's issue. I expected %townyadvanced_town_tag_override% to be my town name or tag in the tablist, but it showed the raw placeholder name: "%townyadvanced_town_tag_override%". This applies to %townyadvanced_nation_tag_override% aswell

### Towny version

Towny 0.100.1.5

### Server version

Minehut - Paper 1.19.4

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
2. Your Towny config.yml: https://pastebin.com/Ndcp5MKr
3. Your townyperms.yml: https://pastebin.com/kVneZmN7
4. Your log's error: https://pastebin.com/5DhFUFTm
5. TAB groups.yml: https://pastebin.com/PdQmr3RB
6. TAB config.yml: https://pastebin.com/XGzGbDuQ

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
You can't do this:

```
  papi_chat_formatting:
 
    # When using PlaceholderAPI, and a tag would show both nation and town, this will determine how they are formatted.
    both: '%rel_townyadvanced_color%[%n][%t] '
 
    # When using PlaceholderAPI, and a tag would showing a town, this will determine how it is formatted.
    town: '%rel_townyadvanced_color%[%s] '
 
    # When using PlaceholderAPI, and a tag would show a nation, this will determine how it is formatted.
    nation: '%rel_townyadvanced_color%[%s] '
```

You cannot put relational or any placeholder in your config's placeholder formatting section.
