### ISSUE TITLE
Chunks are regenerating empty down to void

### ISSUE THREAD

**Issue by Parthodys** [TownyAdvanced/Towny#7411]
### What steps will reproduce the problem?

1. Claim an area
2. Unclaim the area after some time
3. Towny makes empty gaps down to void into some chunks

The chunks seem to usually be about half-empty. Most chunks are still seemingly regenerated normally, but many are starting to have gaps. Chunk regeneration has worked fine for years until now. Also our world only goes down to 0 Y.

![2024-05-08_10 54 11](https://github.com/TownyAdvanced/Towny/assets/1515422/16975510-80ce-47ef-83b5-e94c1a2cd119)
<img width="631" alt="void_holes" src="https://github.com/TownyAdvanced/Towny/assets/1515422/eb47afd2-03ad-4de3-bd86-621d22ac60be">
<img width="1364" alt="Broken_chunk" src="https://github.com/TownyAdvanced/Towny/assets/1515422/3be5cfc4-6e75-4c92-8f3e-d9bb864fca63">

### What is the expected output?

Chunks should regenerate properly and not have empty gaps down to void.

### Towny version

0.100.2.1

### Server version

Paper-318, 1.20.2

### Please use Pastebin.com to link the following files

1. No errors/problems in startup
2. Can't provide publicly, which part needed?
```
    revert_on_unclaim:
      enabled: 'true'
      speed: 1s
      block_ignore: CHEST,TRAPPED_CHEST,RAIL,POWERED_RAIL,DETECTOR_RAIL,ACTIVATOR_RAIL,TORCH,WALL_TORCH,SPAWNER,ANCIENT_DEBRIS,TNT,AIR,CRAFTING_TABLE,DRAGON_EGG,CRYING_OBSIDIAN,SNOW,MOVING_PISTON
      block_whitelist: ''
```
3. Can't provide publicly, which part needed?
4. Only this error has popped up, but not directly when unclaiming, https://pastebin.com/XXYbgjyj
