### ISSUE TITLE
Dynmap-Towny: Regressions in plot type rendering

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#7462]
### What steps will reproduce the problem?

In version 1.1.2, the following no longer work:

- Plot type colors
- Clicking on a plot no longer tells you its type

![image](https://github.com/TownyAdvanced/Towny/assets/6566982/269102d9-5df5-45f4-bf5d-c02e5b468cb6)
(Screenshot taken from prod instance.)

```
townblock_colours:
  shops:
  
    # Show shop plots with their own fill colour.
    showshops: 'true'
  
    # The colour shops plots are filled with.
    fillcolour: '#FFFF00'
  arenas:
  
    # Show arena plots with their own fill colour.
    showarenas: 'true'
  
    # The colour arena plots are filled with.
    fillcolour: '#FF0000'
  embassies:
  
    # Show embassy plots with their own fill colour.
    showembassies: 'true'
  
    # The colour embassy plots are filled with.
    fillcolour: '#000000'
  wilds:
  
    # Show wilds plots with their own fill colour.
    showwilds: 'true'
  
    # The colour wilds plots are filled with.
    fillcolour: '#00FF00'
```

### What is the expected output?

In version 0.94, the following worked perfectly:

- Plot type colors
- Clicking on a plot tells you its type

![image](https://github.com/TownyAdvanced/Towny/assets/6566982/6dfe1d82-f1d1-4f78-8f48-71cda4655d83)
![image](https://github.com/TownyAdvanced/Towny/assets/6566982/87d5f7de-4ae2-40bd-860e-1427bf66dfef)
![image](https://github.com/TownyAdvanced/Towny/assets/6566982/a5e4b1c4-fc0f-46a4-92ac-e12c4ea290e0)
(Forgive the ugly map; these screenshots are from a local development server that does not have a copy of the live world.)

```
  fillColorShops: '#FFFF00'
  fillColorArenas: '#FF0000'
  fillColorEmbassies: '#000000'
  fillColorWilds: '#00FF00'
```

### Towny version

`1.100.3.0`.  Varying just the version of Dynmap-Towny results in the above discrepancies.

### Server version

Paper version `git-Paper-411` (MC: `1.17.1`) (Implementing API version `1.17.1-R0.1-SNAPSHOT`) (Git: `6625db3` on `ver/1.17.1`)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: Unfortunately nothing interesting in the log, so not going through the trouble of gisting it.
2. Your Towny config.yml: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Towny/settings/config.yml
3. Dynmap-Towny config: https://github.com/SettleScape/server/blob/master/minecraft/plugins/Dynmap-Towny/config.yml
4. Your log's error: No error.
