### ISSUE TITLE
&6 appearing in using_titles nationname

### ISSUE THREAD

**Issue by ewof** [TownyAdvanced/Towny#7797]
### What steps will reproduce the problem?

using_titles: 'true' in config and use nationname one anywhere

### What is the expected output?

just the nation name

### Towny version

0.101.1.6

### Server version

folia 1.21.4

### Please use Pastebin.com to link the following files

![Image](https://github.com/user-attachments/assets/1f954884-9023-4830-a78b-ea2c16144bed)

this is with
```yml
  titles:
  
    # Entering Town Upper Title Line
    town_title: '&b{townname}'
  
    # Entering Town Lower Subtitle line.
    town_subtitle: '&6{nationname}'
```
if i remove the &6 from town_subtitle the &6 will still be there in the nation name but the text will be white, also happens if nationname is in town_title
