### ISSUE TITLE
ASCII map symbols loading problem

### ISSUE THREAD

**Issue by FemboyFanClub** [TownyAdvanced/Towny#7801]
### What steps will reproduce the problem?

1. Go to the towny config and change the towny map symbols. For example, like this:
```
ascii_map_symbols:
  
  # The character used for the home symbol.
  home: "\u0264"
  
  # The character used for the outpost symbol.
  outpost: "\u025F"
  
  # The character used for plots which are forsale.
  forsale: "\u0261"
  
  # The character used for plots which are unclaimed.
  wilderness: "\u0260"
  
  # The height of the map shown in /towny map and /res toggle map.
  # Minimum 7, maximum 18.
  map_height: '9'
  
  # The width of the map shown in /towny map and /res toggle map.
  # Minimum 7, maximum 27, only odd numbers are accepted.
  map_width: '23'
```
2. Start the server;
3. Join and use command `/towny map`;
4. You may notice that the **symbols have not changed!**
5. Use `/townyadmin reload all` command
6. Only now the symbols have changed.

### What is the expected output?

I expected that map symbols to change when the plugin fully loaded and not after the full reload.

### Towny version

Towny-0.101.1.0

### Server version

paper-1.21.4-211

### Please use Pastebin.com to link the following files

–

**Comment by LlmDl** [comment]
Have you tried putting the actual unicode character into the config, instead of the code?

**Comment by FemboyFanClub** [comment]
Also, map keys for `townblocktypes` working correctly. For example:

```
townblocktypes:
  types:
  - name: default
    cost: 0.0
    tax: 0.0
    mapKey: ɘ
    colour: ''
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: ''
  - name: shop
    cost: 0.0
    tax: 0.0
    mapKey: ɢ
    colour: <blue>
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: ''
  - name: arena
    cost: 0.0
    tax: 0.0
    mapKey: ɖ
    colour: ''
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: ''
  - name: embassy
    cost: 0.0
    tax: 0.0
    mapKey: ɚ
    colour: ''
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: ''
  - name: wilds
    cost: 0.0
    tax: 0.0
    mapKey: ɜ
    colour: ''
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: GOLD_ORE,IRON_ORE,COAL_ORE,COPPER_ORE,REDSTONE_ORE,EMERALD_ORE,LAPIS_ORE,DIAMOND_ORE,DEEPSLATE_COAL_ORE,DEEPSLATE_IRON_ORE,DEEPSLATE_COPPER_ORE,DEEPSLATE_GOLD_ORE,DEEPSLATE_EMERALD_ORE,DEEPSLATE_REDSTONE_ORE,DEEPSLATE_LAPIS_ORE,DEEPSLATE_DIAMOND_ORE,NETHER_GOLD_ORE,NETHER_QUARTZ_ORE,ANCIENT_DEBRIS,OAK_LOG,SPRUCE_LOG,BIRCH_LOG,JUNGLE_LOG,ACACIA_LOG,DARK_OAK_LOG,CRIMSON_STEM,WARPED_STEM,ACACIA_LEAVES,OAK_LEAVES,DARK_OAK_LEAVES,JUNGLE_LEAVES,BIRCH_LEAVES,SPRUCE_LEAVES,CRIMSON_HYPHAE,WARPED_HYPHAE,ACACIA_SAPLING,BAMBOO_SAPLING,BIRCH_SAPLING,DARK_OAK_SAPLING,JUNGLE_SAPLING,OAK_SAPLING,SPRUCE_SAPLING,TALL_GRASS,BROWN_MUSHROOM,RED_MUSHROOM,CACTUS,ALLIUM,AZURE_BLUET,BLUE_ORCHID,CORNFLOWER,DANDELION,LILAC,LILY_OF_THE_VALLEY,ORANGE_TULIP,OXEYE_DAISY,PEONY,PINK_TULIP,POPPY,RED_TULIP,ROSE_BUSH,SUNFLOWER,WHITE_TULIP,WITHER_ROSE,CRIMSON_FUNGUS,LARGE_FERN,TORCH,LADDER,CLAY,PUMPKIN,GLOWSTONE,VINE,NETHER_WART_BLOCK,COCOA
  - name: inn
    cost: 0.0
    tax: 0.0
    mapKey: ɝ
    colour: ''
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: ''
  - name: jail
    cost: 0.0
    tax: 0.0
    mapKey: ɞ
    colour: ''
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: ''
  - name: farm
    cost: 0.0
    tax: 0.0
    mapKey: ɛ
    colour: ''
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: BROWN_MUSHROOM,MELON_SEEDS,MANGROVE_LEAVES,ATTACHED_PUMPKIN_STEM,POTTED_PALE_OAK_SAPLING,SHEARS,ACACIA_LOG,POTTED_ACACIA_SAPLING,CHERRY_SAPLING,CLOSED_EYEBLOSSOM,TWISTING_VINES_PLANT,MELON_STEM,PINK_TULIP,PALE_OAK_LOG,TORCHFLOWER,JUNGLE_SAPLING,OAK_WOOD,WHITE_TULIP,CACTUS,SPRUCE_WOOD,CRIMSON_ROOTS,BAMBOO_SAPLING,BLUE_ORCHID,PUMPKIN,NETHER_WART_BLOCK,FLOWERING_AZALEA_LEAVES,WHEAT,PINK_PETALS,SPRUCE_LOG,RED_MUSHROOM,AZALEA,SPRUCE_SAPLING,SMALL_DRIPLEAF,PITCHER_POD,CRIMSON_FUNGUS,TALL_GRASS,POTTED_BIRCH_SAPLING,DARK_OAK_SAPLING,CHORUS_FLOWER,POTTED_OAK_SAPLING,BAMBOO_BLOCK,SUNFLOWER,CORNFLOWER,PUMPKIN_STEM,POTATOES,TORCHFLOWER_SEEDS,PITCHER_PLANT,WARPED_ROOTS,COCOA_BEANS,POPPY,DARK_OAK_WOOD,POTTED_JUNGLE_SAPLING,CRIMSON_HYPHAE,DARK_OAK_LOG,KELP,LILAC,POTTED_SPRUCE_SAPLING,VINE,PALE_OAK_LEAVES,CHERRY_WOOD,CRIMSON_STEM,NETHER_SPROUTS,ATTACHED_MELON_STEM,WARPED_WART_BLOCK,ACACIA_LEAVES,CHERRY_LOG,PALE_OAK_WOOD,LARGE_FERN,MANGROVE_LOG,BAMBOO,PITCHER_CROP,SUGAR_CANE,COW_SPAWN_EGG,GOAT_SPAWN_EGG,MOOSHROOM_SPAWN_EGG,JUNGLE_LEAVES,JUNGLE_WOOD,CHERRY_LEAVES,PUMPKIN_SEEDS,SPORE_BLOSSOM,RED_TULIP,POTTED_CHERRY_SAPLING,WARPED_FUNGUS,JUNGLE_LOG,NETHER_WART,WARPED_HYPHAE,FLOWERING_AZALEA,LILY_OF_THE_VALLEY,DANDELION,AZALEA_LEAVES,COCOA,ALLIUM,ACACIA_WOOD,SHROOMLIGHT,WARPED_STEM,OPEN_EYEBLOSSOM,MANGROVE_WOOD,OAK_SAPLING,PEONY,WEEPING_VINES_PLANT,AZURE_BLUET,OXEYE_DAISY,DARK_OAK_LEAVES,PALE_OAK_SAPLING,MELON,WHEAT_SEEDS,WITHER_ROSE,ACACIA_SAPLING,BIRCH_SAPLING,OAK_LOG,BEETROOTS,BIG_DRIPLEAF,BIRCH_LOG,CARROTS,BIRCH_WOOD,POTTED_DARK_OAK_SAPLING,OAK_LEAVES,SEA_PICKLE,SPRUCE_LEAVES,BEETROOT_SEEDS,SWEET_BERRY_BUSH,CHORUS_FRUIT,BIRCH_LEAVES,ORANGE_TULIP,MANGROVE_PROPAGULE,ROSE_BUSH
  - name: bank
    cost: 0.0
    tax: 0.0
    mapKey: ɗ
    colour: ''
    itemUseIds: ''
    switchIds: ''
    allowedBlocks: ''
```

Once the plugin is fully loaded, these symbols will be applied for the plot types without towny full reload.
